server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: currency-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/currency_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: Admin1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: currency_service
    user: root
    password: Admin1!
springdoc:
  api-docs:
    path: currency-service/v3/api-docs